### ISSUE TITLE
:bug:[BUG] 深色主题没有进行适配，无法看清内容

### ISSUE THREAD

**Issue by KINOVE** [LaoZhuJackson/SnowbreakAutoAssistant#1]
如图所示，无法看清内容。

由于软件默认设置主题为“跟随系统设置”，且深色主题未适配，需要手动调整为浅色后才能正常看清文字。

![image](https://github.com/user-attachments/assets/bd58433f-f3eb-449f-8db9-3c5f722c7f2d)

![image](https://github.com/user-attachments/assets/e9e42978-f39b-45ee-b295-6b060d393764)

**Comment by LaoZhuJackson** [comment]
这个确实还没进行适配，先用着浅色

**Comment by yegetables** [comment]
+1
