### ISSUE TITLE
每日任务购买完体力后无法正确转到商店

### ISSUE THREAD

**Issue by RomioLA** [LaoZhuJackson/SnowbreakAutoAssistant#10]
复现2次了，日志如下。感谢大佬！

19:16:21 - INFO - 当前任务：领取体力
19:16:23 - DEBUG - 目标图片：app/resource/images/get_power/friends.png 相似度：0.59
19:16:24 - DEBUG - 目标图片：app/resource/images/get_power/friends.png 相似度：0.59
19:16:25 - DEBUG - 目标图片：app/resource/images/get_power/friends.png 相似度：0.98
19:16:26 - DEBUG - 鼠标移动后点击 (1289, 993)
19:16:26 - DEBUG - OCR识别结果: ['键收赠']
19:16:26 - DEBUG - 目标文字：键收赠 相似度：1.00
19:16:27 - DEBUG - 鼠标移动后点击 (2760, 1539)
19:16:27 - DEBUG - 键盘按下 esc
19:16:28 - DEBUG - 未识别出任何文字
19:16:28 - DEBUG - 目标文字：供应站 未找到匹配文字
19:16:30 - DEBUG - OCR识别结果: ['阿木', '79/240', '26290', 'o', '1590000', '+', '+', 'QQ', '等级', '61', '0', '9', '來至北初星', '完成主线故事【困难】', '任务', 'HCL6-4', '?21天', '战斗', '今日收取的感知已达20点上限', '供应站', '星海凭证', '共鸣', '活动', 'o基地', 'ii', '角色', '5天', 'iuuu:终于要断掉一期金框.', '图鉴', '背包', '商店', '8']
19:16:30 - DEBUG - 目标文字：供应站 相似度：0.94
19:16:30 - DEBUG - 鼠标移动后点击 (1148, 1085)
19:16:31 - DEBUG - 目标图片：app/resource/images/get_power/supply_station.png 相似度：0.40
19:16:32 - DEBUG - 目标图片：app/resource/images/get_power/supply_station.png 相似度：1.00
19:16:33 - DEBUG - 鼠标移动后点击 (1006, 956)
19:16:34 - DEBUG - OCR识别结果: ['26290', 'A', '限时补给箱', '日常补给箱', '①21天', '①2送', '①21送', '每日物资配给箱', '凉抚·每周天启者聘任包', '涛·天启者聘任包', '浪涌·武器定制包', '￥16', '128', '①7天']
19:16:34 - DEBUG - 目标文字：每日物资配给箱 相似度：0.98
19:16:34 - DEBUG - 鼠标移动后点击 (1326, 1194)
19:16:35 - DEBUG - OCR识别结果: ['26290', '+', '0', '供应立占/补给箱', '+', '限时补给箱', '日常补给箱', '@2送', '@2送', '@2送', '每日物资备配给箱', '涛·天启者聘任包', '浪涌·武器定制包', '￥16', '凉抚·每周天启者聘任包：', '￥ 128', '￥ 128', '①7天', '@7天', '2', '①21天']
19:16:35 - DEBUG - 目标文字：购买 未找到匹配文字

**Comment by LaoZhuJackson** [comment]
你用的是最新版本嘛，最新版本应该没有问题，你这里日志没给到商店的部分

**Comment by RomioLA** [comment]
我是从Releases下载的1.1.4，打开软件后显示是1.1.3。根据提示，在软件内更新并且剪切替换后，打开的还是1.1.3

**Comment by LaoZhuJackson** [comment]
没事，1,1,3是我忘记更新版本号了，你日志没取到关键部分我不好判断，有可能是间隔太快了导致任务切换的时候没接上

**Comment by ESLI9527** [comment]
基本上应该都是领取之后,esc按的太快，但是界面实际没有退出的缘故。在进入到商店购买任务的时候，实际界面还在供应站的补给箱界面。我翻了下我这的日志，同一秒和下一秒的esc都没有实际退出。不过我这的版本应该还是1.4的，还没更新到1.5，明天再试试了。

**Comment by LaoZhuJackson** [comment]
> 基本上应该都是领取之后,esc按的太快，但是界面实际没有退出的缘故。在进入到商店购买任务的时候，实际界面还在供应站的补给箱界面。我翻了下我这的日志，同一秒和下一秒的esc都没有实际退出。不过我这的版本应该还是1.4的，还没更新到1.5，明天再试试了。

接下来会尝试修复
