### ISSUE TITLE
记忆补嵌包使用识别问题

### ISSUE THREAD

**Issue by ESLI9527** [LaoZhuJackson/SnowbreakAutoAssistant#11]
1.5版本试用了下，还会出现这个问题，应该是偶发性的，就很迷惑。不过我的补给包今天试--第三个速战不能正常识别的问题（1.5貌似解决了，旧日志的原因是速战位置是500，但是限制了只能450以内的）的时候用完了，看看有没有其他人有这个情况复现了。

问题现象：点击使用记忆补嵌包后，概率出现不点击确定的情况。

下面是日志：
![每日碎片](https://github.com/user-attachments/assets/6a4c2951-92a3-418b-ab2f-1fe121c74f50)

11:12:08 - DEBUG - OCR识别结果: ['0/12']
记忆嵌片更新成功：0

11:12:09 - DEBUG - OCR识别结果: ['个人故事', '画', '0/12', '+', '次数：', '0/2', '次数：', '0/2', '次数：', '0/2', '次数', 'ija', '幽潮', '龙舌兰', '朝翼', '豹豹', '辉耀', '茉莉安', '薇蒂雅', '凯茜娅', '伊切尔', '芬妮', '主线故事', '常规行动', '特别派遣', '个人故事', '超元链接', '@', 'o']
11:12:09 - DEBUG - 目标文字：超元链接 相似度：1.00
11:12:10 - DEBUG - 鼠标移动 (1158, 826)
11:12:10 - DEBUG - 滚轮滚动 49700 次
尝试使用2个记忆嵌片

11:12:10 - DEBUG - 目标图片：app/resource/images/person/add_power.png 相似度：1.00
11:12:11 - DEBUG - 鼠标移动后点击 (1568, 52)
11:12:11 - DEBUG - 未识别出任何文字
11:12:11 - DEBUG - 目标文字：暂时没有该类道具 未找到匹配文字
11:12:11 - DEBUG - 目标图片：app/resource/images/person/add_num.png 相似度：1.00
11:12:12 - DEBUG - 鼠标移动后点击 (1221, 626)
11:12:13 - DEBUG - OCR识别结果: ['A提示', '是否将2记忆补嵌包兑换成6记忆嵌片', '6', '®', '最大', 'α取消', '2', '?确定', '主线故事', '黑\u3000常规行动', '。特别派遣', '个人故事', '超元链接']
11:12:13 - DEBUG - 目标文字：确定 未找到匹配文字
11:12:14 - DEBUG - OCR识别结果: ['A提示', '是否将2记忆补嵌包兑换成6记忆嵌片', '6', '+', '最大', 'α取消', '2', '?确定', '主线故事', '黑\u3000常规行动', '。特别派遣', '个人故事', '超元链接']
11:12:14 - DEBUG - 目标文字：确定 未找到匹配文字
11:12:16 - DEBUG - OCR识别结果: ['A提示', '是否将2记忆补嵌包兑换成6记忆嵌片', '6', '+', '最大', 'α取消', '2', '?确定', '主线故事', '黑\u3000常规行动', '。特别派遣', '个人故事', '超元链接']
11:12:16 - DEBUG - 目标文字：确定 未找到匹配文字
11:12:17 - DEBUG - 键盘按下 esc
11:12:18 - DEBUG - OCR识别结果: ['个人故事', '国', '0/12', '+', '0/2', '次数：0/2\u3000', '次数：', '次数：', '0/2', '久委', '龙舌兰', '豹豹', '朝翼', '幽潮', '辉耀', '茉莉安', '薇蒂雅', '凯茜娅', '伊切尔', '芬妮', '主线故事', '常规行动', '特别派遣', '个人故事', '超元链接']
11:12:18 - DEBUG - 目标文字：豹豹 相似度：1.00
11:12:18 - DEBUG - 目标文字：['速战'] 未找到匹配文字
没找到速战position：(None, None)

豹豹未达成速战条件或无刷取次数

豹豹速战未成功

11:12:18 - DEBUG - OCR识别结果: ['0/12']
记忆嵌片更新成功：0

**Comment by LaoZhuJackson** [comment]
这个问题在于确定识别到“?确定”去了，代码很容易改，感谢反馈，描述的很详细

**Comment by ESLI9527** [comment]
对了，提个建议：把日志文件单独放个文件夹吧，这样有历史日志的时候也好找。
之前按停止停不下来的时候，想拿历史日志都不行。
不过这样又要有清除历史日志的操作了，看你的选择吧。

**Comment by LaoZhuJackson** [comment]
> 对了，提个建议：把日志文件单独放个文件夹吧，这样有历史日志的时候也好找。
> 之前按停止停不下来的时候，想拿历史日志都不行。
> 不过这样又要有清除历史日志的操作了，看你的选择吧。

已经写好了，下个版本会加上
