### ISSUE TITLE
更改钓鱼的逻辑

### ISSUE THREAD

**Issue by git1677967754** [LaoZhuJackson/SnowbreakAutoAssistant#13]
需求描述：钓鱼使用模拟键盘键入**空格**的进行实现，但尘白禁区钓鱼按键与翻滚闪避绑定在一起，所以如果更改默认的翻滚闪避键位就会发生钓鱼无法使用。
改进思路：
1. 加入自定义模拟按键；
2. 更改实现逻辑，更换为模拟鼠标点击。

**Comment by LaoZhuJackson** [comment]
> 需求描述：钓鱼使用模拟键盘键入**空格**的进行实现，但尘白禁区钓鱼按键与翻滚闪避绑定在一起，所以如果更改默认的翻滚闪避键位就会发生钓鱼无法使用。
> 改进思路：
> 1. 加入自定义模拟按键；
> 2. 更改实现逻辑，更换为模拟鼠标点击。

小众需求，之后考虑
