### ISSUE TITLE
[feature] 新增 ADB 连接方式

### ISSUE THREAD

**Issue by pandacase** [LaoZhuJackson/SnowbreakAutoAssistant#19]
参考另一个 [Snowbreak assistant](https://github.com/overflow65537/MAA_SnowBreak) 的做法，提供 win 和 安卓 （ADB） 两种连接方式。

后者因为运行环境是模拟器虚拟机，所以不需要保持窗口置顶，也不会抢主机的鼠标，好处大大滴有。纯 win 还是太局限了。

星铁的一个著名 [auto 仓库](https://github.com/LmeSzinc/StarRailCopilot) 也是这种做法）

**Comment by LaoZhuJackson** [comment]
那你直接用maa_snowbreak不就好了嘛，目前不考虑做后台，没精力没时间没必要，和群里的老哥讨论过，大家也不想再在模拟器再下载一个尘白

**Comment by pandacase** [comment]
一个游戏同时用 2 个 AA 也太蛋疼了，这不是看上了您这一个的 GUI 更美观功能更丰富嘛。没精力没时间可以理解，作者辛苦了。

不过没必要就说不过去了，我认为不构成理由，因为只新增途径而不是替换途径只有好处没有坏处，懒得整模拟器的用户可以选择继续原来的方案。

应该说是没精力和没时间的因素权重超过了这个特性带来的优点。20G硬盘换永久不抢占主机 focus，这种一劳永逸的做法不就是程序存在的意义吗

**Comment by LaoZhuJackson** [comment]
> 一个游戏同时用 2 个 AA 也太蛋疼了，这不是看上了您这一个的 GUI 更美观功能更丰富嘛。没精力没时间可以理解，作者辛苦了。
> 
> 不过没必要就说不过去了，我认为不构成理由，因为只新增途径而不是替换途径只有好处没有坏处，懒得整模拟器的用户可以选择继续原来的方案。
> 
> 应该说是没精力和没时间的因素权重超过了这个特性带来的优点。20G硬盘换永久不抢占主机 focus，这种一劳永逸的做法不就是程序存在的意义吗

把别人已经做出来的东西我又做一遍就是没必要，现在尘白是有后台方案的，用win32api就能实现，你应该没看closed的issue就提出了这个，其实你去另一边提让他们加gui比在这里提重复的issue可能会更有效
