### ISSUE TITLE
.exe文件被Windows defence隔离

### ISSUE THREAD

**Issue by trinWhoots** [LaoZhuJackson/SnowbreakAutoAssistant#20]
![image](https://github.com/user-attachments/assets/9738b0a5-774d-44ae-bd0e-e572b2909a44)

**Comment by trinWhoots** [comment]
可能是我设备的问题

**Comment by Euphrates717** [comment]
![Image](https://github.com/user-attachments/assets/40eabfa7-caa2-467b-8a79-7de373dd5343)
严重的已隔离威胁
