### ISSUE TITLE
无法下载ocr组件

### ISSUE THREAD

**Issue by Lon-dawn** [LaoZhuJackson/SnowbreakAutoAssistant#8]
请问有没有其他下载途径？
![bug](https://github.com/user-attachments/assets/ea1f25c9-bd12-4b3a-b626-a2a64bca76e4)

**Comment by LaoZhuJackson** [comment]
https://github.com/hiroi-sora/PaddleOCR-json/releases/download/v1.4.1/PaddleOCR-json_v1.4.1_windows_x64.7z，文件解压后放在./app/common/ppOCR/PaddleOCR-json_v1.4.1_windows_x64
